name: Proxy CI

on:
  push:
    # Run on the main branch
    branches:
      - main
  # Also on PRs, just be careful not to publish anything
  pull_request:
  # Allow to be called from other workflows (like "release")
  workflow_call:
  # But don't trigger on tags, as they are covered by the "release.yaml" workflow

jobs:
  proxy-fails-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install policy server
        run: curl -L -s --output seedwing-policy-server https://github.com/seedwing-io/seedwing-policy/releases/download/v0.1.0-alpha.6/seedwing-policy-server-linux-amd64 && chmod 755 seedwing-policy-server
          
      - name: Install proxy
        run: curl -L -s https://github.com/seedwing-io/seedwing-proxy/releases/download/v0.1.0-alpha.1/seedwing-proxy-x86_64-unknown-linux-gnu.tar.gz | tar xzf - seedwing-proxy

      - name: Run proxy in background
        run: ./seedwing-proxy -c config/maven-proxy.toml &

      - name: Run policy server in background
        run: ./seedwing-policy-server -p policies &

        # Verify servers are up?
        
      - name: Build java app
        run: |
          mkdir -p ~/.m2
          cp maven-home/conf/settings.xml ~/.m2
          cd java && ./mvnw compile

        
